name: client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  firebase_messaging: ^9.1.3
  cloud_firestore: ^1.0.7
  firebase_remote_config: ^0.10.0-dev.2
  flutter_local_notifications: ^5.0.0+3
  firebase_crashlytics: "^2.0.2"

  # Google Maps
  google_sign_in: ^5.0.2
  flutter_polyline_points: ^1.0.0
  geolocator: ^7.0.3

  timeago: ^3.0.2
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  persistent_bottom_nav_bar: ^4.0.2
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  flutter_slidable: ^0.6.0
  google_maps_flutter: ^2.0.3
  smooth_page_indicator: ^0.3.0-nullsafety.0
  formz: ^0.4.0
  provider: ^5.0.0
  pedantic: ^1.11.0
  url_launcher: ^6.0.3
  package_info: ^2.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  dio: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  place_picker: ^0.9.19-nullsafety
  smooth_star_rating:
    git:
      url: https://github.com/bhavin-concetto/smoothratingbar.git
      ref: dev
  built_value: ^8.0.2
  fluttercontactpicker: ^4.4.0
  another_flushbar: ^1.10.20

  authentication_repository:
    path: ../../../mobile/authentication_repository
  user_repository:
    path: ../../../mobile/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.1
  built_value_generator: ^8.0.5

dependency_overrides:
  build_config: ^1.0.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/onboarding/backdrop.jpg
    - assets/onboarding/time_management.png
    - assets/onboarding/anywhere.png
    - assets/onboarding/driver.png
    - assets/brand/logo_with_brand.png
    - assets/brand/gray_icon.png
    - assets/brand/logo_horizontal.jpg
    - assets/undraw/street_food.png
    - assets/undraw/deliveries.png
    - assets/undraw/game_day.png
    - assets/rideshare/
    - assets/rideshare-icons/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
    - family: Kometa
      fonts:
        - asset: assets/fonts/Kometa-Bk.ttf
          weight: 900
        - asset: assets/fonts/Kometa-BkIt.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Kometa-Bld.ttf
          weight: 700
        - asset: assets/fonts/Kometa-BldIt.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Kometa-Hv.ttf
          weight: 800
        - asset: assets/fonts/Kometa-HvIt.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Kometa-Lt.ttf
          weight: 300
        - asset: assets/fonts/Kometa-LtIt.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Kometa-Med.ttf
          weight: 500
        - asset: assets/fonts/Kometa-MedIt.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Kometa-Reg.ttf
          weight: 400
        - asset: assets/fonts/Kometa-RegIt.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Kometa-Th.ttf
          weight: 100
        - asset: assets/fonts/Kometa-ThIt.ttf
          weight: 100
          style: italic
